# Dockerfile-php
FROM php:8.1-fpm

# Обновляем пакеты и устанавливаем зависимости
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    zip \
    unzip \
 && docker-php-ext-configure gd --with-freetype --with-jpeg \
 && docker-php-ext-install -j$(nproc) gd pdo pdo_mysql

# Устанавливаем рабочую директорию
WORKDIR /var/www/html

# Открываем порт 9000 для PHP-FPM (внутреннее соединение с Nginx)
EXPOSE 9000

# Запускаем PHP-FPM
CMD ["php-fpm"]
