version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "9000:9000"         # Map external port 9000 to container port 9000
    environment:
      - PORT=9000           # Set PORT environment variable
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./:/var/www/html
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    volumes:
      - ./:/var/www/html

  db:
    image: mariadb:latest
    env_file:
      - .env
    ports:
      - "42756:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
