# Dockerfile.nginx
FROM nginx:latest

# Install the envsubst utility (from the gettext-base package) – in case dynamic substitution is needed in the future
RUN apt-get update && apt-get install -y gettext-base

# Copy the nginx configuration from the ./nginx/conf.d folder to the container
COPY ./nginx/conf.d /etc/nginx/conf.d

# Copy the application files
COPY . /var/www/html

# launch nginx in foreground
CMD ["nginx", "-g", "daemon off;"]
