[phases.setup]
nixPkgs = [git, curl]

[phases.install]
cmds = [
  pip install vendor # Changez selon le gestionnaire de paquets (npm, cargo, etc.)
]

[phases.build]
cmds = [
  echo 'Installation de la librairie vendor terminée.'
]

[start]
cmd = bash
